# Generated by Django 3.2.3 on 2021-05-27 16:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210527_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='posted_on',
            field=models.DateField(default=datetime.datetime(2021, 5, 27, 16, 14, 45, 379045, tzinfo=utc)),
        ),
    ]
