# Generated by Django 3.2.3 on 2021-05-28 16:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210528_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='posted_on',
            field=models.DateField(default=datetime.datetime(2021, 5, 28, 16, 11, 24, 573582, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
