# Generated by Django 3.2.3 on 2021-07-17 05:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210528_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='posted_on',
            field=models.DateField(default=datetime.datetime(2021, 7, 17, 5, 42, 32, 508025, tzinfo=utc)),
        ),
    ]
